// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: policy/kasregistry/key_access_server_registry.proto

package kasregistry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	KeyAccessServerRegistryService_ListKeyAccessServers_FullMethodName      = "/policy.kasregistry.KeyAccessServerRegistryService/ListKeyAccessServers"
	KeyAccessServerRegistryService_GetKeyAccessServer_FullMethodName        = "/policy.kasregistry.KeyAccessServerRegistryService/GetKeyAccessServer"
	KeyAccessServerRegistryService_CreateKeyAccessServer_FullMethodName     = "/policy.kasregistry.KeyAccessServerRegistryService/CreateKeyAccessServer"
	KeyAccessServerRegistryService_UpdateKeyAccessServer_FullMethodName     = "/policy.kasregistry.KeyAccessServerRegistryService/UpdateKeyAccessServer"
	KeyAccessServerRegistryService_DeleteKeyAccessServer_FullMethodName     = "/policy.kasregistry.KeyAccessServerRegistryService/DeleteKeyAccessServer"
	KeyAccessServerRegistryService_ListKeyAccessServerGrants_FullMethodName = "/policy.kasregistry.KeyAccessServerRegistryService/ListKeyAccessServerGrants"
	KeyAccessServerRegistryService_CreateKey_FullMethodName                 = "/policy.kasregistry.KeyAccessServerRegistryService/CreateKey"
	KeyAccessServerRegistryService_GetKey_FullMethodName                    = "/policy.kasregistry.KeyAccessServerRegistryService/GetKey"
	KeyAccessServerRegistryService_ListKeys_FullMethodName                  = "/policy.kasregistry.KeyAccessServerRegistryService/ListKeys"
	KeyAccessServerRegistryService_UpdateKey_FullMethodName                 = "/policy.kasregistry.KeyAccessServerRegistryService/UpdateKey"
	KeyAccessServerRegistryService_RotateKey_FullMethodName                 = "/policy.kasregistry.KeyAccessServerRegistryService/RotateKey"
)

// KeyAccessServerRegistryServiceClient is the client API for KeyAccessServerRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyAccessServerRegistryServiceClient interface {
	ListKeyAccessServers(ctx context.Context, in *ListKeyAccessServersRequest, opts ...grpc.CallOption) (*ListKeyAccessServersResponse, error)
	GetKeyAccessServer(ctx context.Context, in *GetKeyAccessServerRequest, opts ...grpc.CallOption) (*GetKeyAccessServerResponse, error)
	CreateKeyAccessServer(ctx context.Context, in *CreateKeyAccessServerRequest, opts ...grpc.CallOption) (*CreateKeyAccessServerResponse, error)
	UpdateKeyAccessServer(ctx context.Context, in *UpdateKeyAccessServerRequest, opts ...grpc.CallOption) (*UpdateKeyAccessServerResponse, error)
	DeleteKeyAccessServer(ctx context.Context, in *DeleteKeyAccessServerRequest, opts ...grpc.CallOption) (*DeleteKeyAccessServerResponse, error)
	// Deprecated
	ListKeyAccessServerGrants(ctx context.Context, in *ListKeyAccessServerGrantsRequest, opts ...grpc.CallOption) (*ListKeyAccessServerGrantsResponse, error)
	// KAS Key Management
	// Request to create a new key in the Key Access Service.
	CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
	// Request to retrieve a key from the Key Access Service.
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
	// Request to list keys in the Key Access Service.
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	// Request to update a key in the Key Access Service.
	UpdateKey(ctx context.Context, in *UpdateKeyRequest, opts ...grpc.CallOption) (*UpdateKeyResponse, error)
	// Request to rotate a key in the Key Access Service.
	RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error)
}

type keyAccessServerRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyAccessServerRegistryServiceClient(cc grpc.ClientConnInterface) KeyAccessServerRegistryServiceClient {
	return &keyAccessServerRegistryServiceClient{cc}
}

func (c *keyAccessServerRegistryServiceClient) ListKeyAccessServers(ctx context.Context, in *ListKeyAccessServersRequest, opts ...grpc.CallOption) (*ListKeyAccessServersResponse, error) {
	out := new(ListKeyAccessServersResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_ListKeyAccessServers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) GetKeyAccessServer(ctx context.Context, in *GetKeyAccessServerRequest, opts ...grpc.CallOption) (*GetKeyAccessServerResponse, error) {
	out := new(GetKeyAccessServerResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_GetKeyAccessServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) CreateKeyAccessServer(ctx context.Context, in *CreateKeyAccessServerRequest, opts ...grpc.CallOption) (*CreateKeyAccessServerResponse, error) {
	out := new(CreateKeyAccessServerResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_CreateKeyAccessServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) UpdateKeyAccessServer(ctx context.Context, in *UpdateKeyAccessServerRequest, opts ...grpc.CallOption) (*UpdateKeyAccessServerResponse, error) {
	out := new(UpdateKeyAccessServerResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_UpdateKeyAccessServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) DeleteKeyAccessServer(ctx context.Context, in *DeleteKeyAccessServerRequest, opts ...grpc.CallOption) (*DeleteKeyAccessServerResponse, error) {
	out := new(DeleteKeyAccessServerResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_DeleteKeyAccessServer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) ListKeyAccessServerGrants(ctx context.Context, in *ListKeyAccessServerGrantsRequest, opts ...grpc.CallOption) (*ListKeyAccessServerGrantsResponse, error) {
	out := new(ListKeyAccessServerGrantsResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_ListKeyAccessServerGrants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_CreateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_GetKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_ListKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) UpdateKey(ctx context.Context, in *UpdateKeyRequest, opts ...grpc.CallOption) (*UpdateKeyResponse, error) {
	out := new(UpdateKeyResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_UpdateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyAccessServerRegistryServiceClient) RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error) {
	out := new(RotateKeyResponse)
	err := c.cc.Invoke(ctx, KeyAccessServerRegistryService_RotateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyAccessServerRegistryServiceServer is the server API for KeyAccessServerRegistryService service.
// All implementations must embed UnimplementedKeyAccessServerRegistryServiceServer
// for forward compatibility
type KeyAccessServerRegistryServiceServer interface {
	ListKeyAccessServers(context.Context, *ListKeyAccessServersRequest) (*ListKeyAccessServersResponse, error)
	GetKeyAccessServer(context.Context, *GetKeyAccessServerRequest) (*GetKeyAccessServerResponse, error)
	CreateKeyAccessServer(context.Context, *CreateKeyAccessServerRequest) (*CreateKeyAccessServerResponse, error)
	UpdateKeyAccessServer(context.Context, *UpdateKeyAccessServerRequest) (*UpdateKeyAccessServerResponse, error)
	DeleteKeyAccessServer(context.Context, *DeleteKeyAccessServerRequest) (*DeleteKeyAccessServerResponse, error)
	// Deprecated
	ListKeyAccessServerGrants(context.Context, *ListKeyAccessServerGrantsRequest) (*ListKeyAccessServerGrantsResponse, error)
	// KAS Key Management
	// Request to create a new key in the Key Access Service.
	CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	// Request to retrieve a key from the Key Access Service.
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	// Request to list keys in the Key Access Service.
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	// Request to update a key in the Key Access Service.
	UpdateKey(context.Context, *UpdateKeyRequest) (*UpdateKeyResponse, error)
	// Request to rotate a key in the Key Access Service.
	RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error)
	mustEmbedUnimplementedKeyAccessServerRegistryServiceServer()
}

// UnimplementedKeyAccessServerRegistryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeyAccessServerRegistryServiceServer struct {
}

func (UnimplementedKeyAccessServerRegistryServiceServer) ListKeyAccessServers(context.Context, *ListKeyAccessServersRequest) (*ListKeyAccessServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeyAccessServers not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) GetKeyAccessServer(context.Context, *GetKeyAccessServerRequest) (*GetKeyAccessServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyAccessServer not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) CreateKeyAccessServer(context.Context, *CreateKeyAccessServerRequest) (*CreateKeyAccessServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyAccessServer not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) UpdateKeyAccessServer(context.Context, *UpdateKeyAccessServerRequest) (*UpdateKeyAccessServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeyAccessServer not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) DeleteKeyAccessServer(context.Context, *DeleteKeyAccessServerRequest) (*DeleteKeyAccessServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyAccessServer not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) ListKeyAccessServerGrants(context.Context, *ListKeyAccessServerGrantsRequest) (*ListKeyAccessServerGrantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeyAccessServerGrants not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKey not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) UpdateKey(context.Context, *UpdateKeyRequest) (*UpdateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKey not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedKeyAccessServerRegistryServiceServer) mustEmbedUnimplementedKeyAccessServerRegistryServiceServer() {
}

// UnsafeKeyAccessServerRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyAccessServerRegistryServiceServer will
// result in compilation errors.
type UnsafeKeyAccessServerRegistryServiceServer interface {
	mustEmbedUnimplementedKeyAccessServerRegistryServiceServer()
}

func RegisterKeyAccessServerRegistryServiceServer(s grpc.ServiceRegistrar, srv KeyAccessServerRegistryServiceServer) {
	s.RegisterService(&KeyAccessServerRegistryService_ServiceDesc, srv)
}

func _KeyAccessServerRegistryService_ListKeyAccessServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeyAccessServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).ListKeyAccessServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_ListKeyAccessServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).ListKeyAccessServers(ctx, req.(*ListKeyAccessServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_GetKeyAccessServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyAccessServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).GetKeyAccessServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_GetKeyAccessServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).GetKeyAccessServer(ctx, req.(*GetKeyAccessServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_CreateKeyAccessServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyAccessServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).CreateKeyAccessServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_CreateKeyAccessServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).CreateKeyAccessServer(ctx, req.(*CreateKeyAccessServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_UpdateKeyAccessServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKeyAccessServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).UpdateKeyAccessServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_UpdateKeyAccessServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).UpdateKeyAccessServer(ctx, req.(*UpdateKeyAccessServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_DeleteKeyAccessServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyAccessServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).DeleteKeyAccessServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_DeleteKeyAccessServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).DeleteKeyAccessServer(ctx, req.(*DeleteKeyAccessServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_ListKeyAccessServerGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeyAccessServerGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).ListKeyAccessServerGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_ListKeyAccessServerGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).ListKeyAccessServerGrants(ctx, req.(*ListKeyAccessServerGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_CreateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).CreateKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_UpdateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).UpdateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_UpdateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).UpdateKey(ctx, req.(*UpdateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyAccessServerRegistryService_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyAccessServerRegistryServiceServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyAccessServerRegistryService_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyAccessServerRegistryServiceServer).RotateKey(ctx, req.(*RotateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyAccessServerRegistryService_ServiceDesc is the grpc.ServiceDesc for KeyAccessServerRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyAccessServerRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "policy.kasregistry.KeyAccessServerRegistryService",
	HandlerType: (*KeyAccessServerRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListKeyAccessServers",
			Handler:    _KeyAccessServerRegistryService_ListKeyAccessServers_Handler,
		},
		{
			MethodName: "GetKeyAccessServer",
			Handler:    _KeyAccessServerRegistryService_GetKeyAccessServer_Handler,
		},
		{
			MethodName: "CreateKeyAccessServer",
			Handler:    _KeyAccessServerRegistryService_CreateKeyAccessServer_Handler,
		},
		{
			MethodName: "UpdateKeyAccessServer",
			Handler:    _KeyAccessServerRegistryService_UpdateKeyAccessServer_Handler,
		},
		{
			MethodName: "DeleteKeyAccessServer",
			Handler:    _KeyAccessServerRegistryService_DeleteKeyAccessServer_Handler,
		},
		{
			MethodName: "ListKeyAccessServerGrants",
			Handler:    _KeyAccessServerRegistryService_ListKeyAccessServerGrants_Handler,
		},
		{
			MethodName: "CreateKey",
			Handler:    _KeyAccessServerRegistryService_CreateKey_Handler,
		},
		{
			MethodName: "GetKey",
			Handler:    _KeyAccessServerRegistryService_GetKey_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _KeyAccessServerRegistryService_ListKeys_Handler,
		},
		{
			MethodName: "UpdateKey",
			Handler:    _KeyAccessServerRegistryService_UpdateKey_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _KeyAccessServerRegistryService_RotateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "policy/kasregistry/key_access_server_registry.proto",
}
