// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization/authorization.proto

// Protobuf Java Version: 3.25.3
package com.authorization;

public interface ResourceAttributesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authorization.ResourceAttributes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>repeated string attribute_id = 2 [json_name = "attributeId"];</code>
   * @return A list containing the attributeId.
   */
  java.util.List<java.lang.String>
      getAttributeIdList();
  /**
   * <code>repeated string attribute_id = 2 [json_name = "attributeId"];</code>
   * @return The count of attributeId.
   */
  int getAttributeIdCount();
  /**
   * <code>repeated string attribute_id = 2 [json_name = "attributeId"];</code>
   * @param index The index of the element to return.
   * @return The attributeId at the given index.
   */
  java.lang.String getAttributeId(int index);
  /**
   * <code>repeated string attribute_id = 2 [json_name = "attributeId"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the attributeId at the given index.
   */
  com.google.protobuf.ByteString
      getAttributeIdBytes(int index);
}
