root = "./service"
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["start"]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./service"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs", "examples"]
  exclude_file = []
  exclude_regex = ["_test.go^", ".tdf^", ".ntdf^"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "rego"]
  include_file = ["opentdf.yaml"]
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = true
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
