version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - durationcheck
    - decorder
    - dogsled
    - durationcheck
    # - err113
    - errcheck
    - errname
    - errorlint
    # - errchkjson
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - gocheckcompilerdirectives
    # - gochecknoinits
    - goconst
    - gocritic
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    # - intrange
    - loggercheck
    - makezero
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    # - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    # - recvcheck
    - rowserrcheck
    # - sloglint
    - spancheck
    - sqlclosecheck
    # - staticcheck
    # - tagalign
    # - tagliatelle # maybe we want this to force consistent config to ensure consistent tag alignment across the codebase
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: satori's package is not maintained
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/google/uuid
              reason: gofrs' package is not go module
    gosec:
      excludes:
        - G115
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    mnd:
      ignored-functions:
        - os.Chmod
        - os.Mkdir
        - os.MkdirAll
        - os.OpenFile
        - os.WriteFile
        - prometheus.ExponentialBuckets
        - prometheus.ExponentialBucketsRange
        - prometheus.LinearBuckets
    nolintlint:
      require-explanation: true
      require-specific: true
    rowserrcheck:
      packages:
        - github.com/jackc/pgx/v5
    sloglint:
      kv-only: true
      no-mixed-args: true
      static-msg: true
      attr-only: false
      no-raw-keys: true
      msg-style: lowercased
      key-naming-case: snake
      forbidden-keys:
        - time
        - level
        - msg
        - source
      args-on-sep-lines: true
    tagliatelle:
      case:
        rules:
          json: snake
          mapstructure: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: ^//\s*go:generate\s
      - linters:
          - godot
        source: (noinspection|TODO)
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - errorlint
        source: ^\s+if _, ok := err\.\([^.]+\.InternalError\); ok {
      - linters:
          - bodyclose
          - dupl
          - funlen
          - goconst
          - gosec
          - lll
          - noctx
          - wrapcheck
        path: _test\.go
      - linters:
          - govet
        text: 'shadow: declaration of "(err)" shadows declaration at'
      - linters:
          - goimport
        text: http://www.apache.org/licenses/LICENSE-2.0
    paths:
      - .*\.pb\.go
      - .*\.pb\.gw.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - .*\.pb\.gw.go
      - third_party$
      - builtin$
      - examples$
