# Use the specified Fluentd base image
FROM fluent/fluentd:v1.17.1-1.0

# Switch to root to install plugins
USER root

# Install the Splunk HEC plugin for Fluentd
RUN gem install fluent-plugin-splunk-hec --no-document

# Revert back to the Fluentd user
USER fluent