sonar.projectKey=opentdf_platform
sonar.organization=opentdf

sonar.sources=.
sonar.exclusions=docs/**,protocol/**,.github/**,examples/**,test/**,**/testdata/**,**/*_test.go,coverage.*

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=coverage.json

sonar.plsql.file.suffixes=pks,pkb
sonar.postgres.file.suffixes=sql,pgsql,psql

sonar.log.level=INFO
