// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentdf/platform/subjectmapping/subject_mapping.proto

// Protobuf Java Version: 3.25.2
package io.opentdf.platform.subjectmapping;

public interface UpdateSubjectMappingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentdf.platform.subjectmapping.UpdateSubjectMappingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.opentdf.platform.subjectmapping.SubjectMappingCreateUpdate subject_mapping = 2 [json_name = "subjectMapping", (.buf.validate.field) = { ... }</code>
   * @return Whether the subjectMapping field is set.
   */
  boolean hasSubjectMapping();
  /**
   * <code>.opentdf.platform.subjectmapping.SubjectMappingCreateUpdate subject_mapping = 2 [json_name = "subjectMapping", (.buf.validate.field) = { ... }</code>
   * @return The subjectMapping.
   */
  io.opentdf.platform.subjectmapping.SubjectMappingCreateUpdate getSubjectMapping();
  /**
   * <code>.opentdf.platform.subjectmapping.SubjectMappingCreateUpdate subject_mapping = 2 [json_name = "subjectMapping", (.buf.validate.field) = { ... }</code>
   */
  io.opentdf.platform.subjectmapping.SubjectMappingCreateUpdateOrBuilder getSubjectMappingOrBuilder();
}
