/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum v1PolicyResourceType {
    POLICY_RESOURCE_TYPE_UNSPECIFIED = 'POLICY_RESOURCE_TYPE_UNSPECIFIED',
    POLICY_RESOURCE_TYPE_RESOURCE_ENCODING = 'POLICY_RESOURCE_TYPE_RESOURCE_ENCODING',
    POLICY_RESOURCE_TYPE_RESOURCE_ENCODING_SYNONYM = 'POLICY_RESOURCE_TYPE_RESOURCE_ENCODING_SYNONYM',
    POLICY_RESOURCE_TYPE_RESOURCE_ENCODING_MAPPING = 'POLICY_RESOURCE_TYPE_RESOURCE_ENCODING_MAPPING',
    POLICY_RESOURCE_TYPE_RESOURCE_ENCODING_GROUP = 'POLICY_RESOURCE_TYPE_RESOURCE_ENCODING_GROUP',
    POLICY_RESOURCE_TYPE_SUBJECT_ENCODING_MAPPING = 'POLICY_RESOURCE_TYPE_SUBJECT_ENCODING_MAPPING',
    POLICY_RESOURCE_TYPE_KEY_ACCESS = 'POLICY_RESOURCE_TYPE_KEY_ACCESS',
    POLICY_RESOURCE_TYPE_ATTRIBUTE_DEFINITION = 'POLICY_RESOURCE_TYPE_ATTRIBUTE_DEFINITION',
    POLICY_RESOURCE_TYPE_ATTRIBUTE_GROUP = 'POLICY_RESOURCE_TYPE_ATTRIBUTE_GROUP',
}
