// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/attributes/attributes.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.attributes;

public interface GetAttributesByFqnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.attributes.GetAttributesByFqnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .policy.attributes.Attribute attributes = 1 [json_name = "attributes"];</code>
   */
  java.util.List<io.opentdf.platform.policy.attributes.Attribute> 
      getAttributesList();
  /**
   * <code>repeated .policy.attributes.Attribute attributes = 1 [json_name = "attributes"];</code>
   */
  io.opentdf.platform.policy.attributes.Attribute getAttributes(int index);
  /**
   * <code>repeated .policy.attributes.Attribute attributes = 1 [json_name = "attributes"];</code>
   */
  int getAttributesCount();
  /**
   * <code>repeated .policy.attributes.Attribute attributes = 1 [json_name = "attributes"];</code>
   */
  java.util.List<? extends io.opentdf.platform.policy.attributes.AttributeOrBuilder> 
      getAttributesOrBuilderList();
  /**
   * <code>repeated .policy.attributes.Attribute attributes = 1 [json_name = "attributes"];</code>
   */
  io.opentdf.platform.policy.attributes.AttributeOrBuilder getAttributesOrBuilder(
      int index);
}
