// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/namespaces/namespaces.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.namespaces;

/**
 * Protobuf type {@code policy.namespaces.GetNamespaceRequest}
 */
public final class GetNamespaceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:policy.namespaces.GetNamespaceRequest)
    GetNamespaceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetNamespaceRequest.newBuilder() to construct.
  private GetNamespaceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetNamespaceRequest() {
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetNamespaceRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_GetNamespaceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_GetNamespaceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.policy.namespaces.GetNamespaceRequest.class, io.opentdf.platform.policy.namespaces.GetNamespaceRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPAND_FIELD_NUMBER = 2;
  private io.opentdf.platform.policy.policy_common.AttributeExpandSelector expand_;
  /**
   * <pre>
   * Optional expand selector
   * </pre>
   *
   * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
   * @return Whether the expand field is set.
   */
  @java.lang.Override
  public boolean hasExpand() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Optional expand selector
   * </pre>
   *
   * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
   * @return The expand.
   */
  @java.lang.Override
  public io.opentdf.platform.policy.policy_common.AttributeExpandSelector getExpand() {
    return expand_ == null ? io.opentdf.platform.policy.policy_common.AttributeExpandSelector.getDefaultInstance() : expand_;
  }
  /**
   * <pre>
   * Optional expand selector
   * </pre>
   *
   * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.policy_common.AttributeExpandSelectorOrBuilder getExpandOrBuilder() {
    return expand_ == null ? io.opentdf.platform.policy.policy_common.AttributeExpandSelector.getDefaultInstance() : expand_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getExpand());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getExpand());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.policy.namespaces.GetNamespaceRequest)) {
      return super.equals(obj);
    }
    io.opentdf.platform.policy.namespaces.GetNamespaceRequest other = (io.opentdf.platform.policy.namespaces.GetNamespaceRequest) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasExpand() != other.hasExpand()) return false;
    if (hasExpand()) {
      if (!getExpand()
          .equals(other.getExpand())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasExpand()) {
      hash = (37 * hash) + EXPAND_FIELD_NUMBER;
      hash = (53 * hash) + getExpand().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.policy.namespaces.GetNamespaceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code policy.namespaces.GetNamespaceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:policy.namespaces.GetNamespaceRequest)
      io.opentdf.platform.policy.namespaces.GetNamespaceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_GetNamespaceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_GetNamespaceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.policy.namespaces.GetNamespaceRequest.class, io.opentdf.platform.policy.namespaces.GetNamespaceRequest.Builder.class);
    }

    // Construct using io.opentdf.platform.policy.namespaces.GetNamespaceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getExpandFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      expand_ = null;
      if (expandBuilder_ != null) {
        expandBuilder_.dispose();
        expandBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_GetNamespaceRequest_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.namespaces.GetNamespaceRequest getDefaultInstanceForType() {
      return io.opentdf.platform.policy.namespaces.GetNamespaceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.policy.namespaces.GetNamespaceRequest build() {
      io.opentdf.platform.policy.namespaces.GetNamespaceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.namespaces.GetNamespaceRequest buildPartial() {
      io.opentdf.platform.policy.namespaces.GetNamespaceRequest result = new io.opentdf.platform.policy.namespaces.GetNamespaceRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentdf.platform.policy.namespaces.GetNamespaceRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.expand_ = expandBuilder_ == null
            ? expand_
            : expandBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.policy.namespaces.GetNamespaceRequest) {
        return mergeFrom((io.opentdf.platform.policy.namespaces.GetNamespaceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.policy.namespaces.GetNamespaceRequest other) {
      if (other == io.opentdf.platform.policy.namespaces.GetNamespaceRequest.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasExpand()) {
        mergeExpand(other.getExpand());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getExpandFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private io.opentdf.platform.policy.policy_common.AttributeExpandSelector expand_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentdf.platform.policy.policy_common.AttributeExpandSelector, io.opentdf.platform.policy.policy_common.AttributeExpandSelector.Builder, io.opentdf.platform.policy.policy_common.AttributeExpandSelectorOrBuilder> expandBuilder_;
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     * @return Whether the expand field is set.
     */
    public boolean hasExpand() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     * @return The expand.
     */
    public io.opentdf.platform.policy.policy_common.AttributeExpandSelector getExpand() {
      if (expandBuilder_ == null) {
        return expand_ == null ? io.opentdf.platform.policy.policy_common.AttributeExpandSelector.getDefaultInstance() : expand_;
      } else {
        return expandBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     */
    public Builder setExpand(io.opentdf.platform.policy.policy_common.AttributeExpandSelector value) {
      if (expandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expand_ = value;
      } else {
        expandBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     */
    public Builder setExpand(
        io.opentdf.platform.policy.policy_common.AttributeExpandSelector.Builder builderForValue) {
      if (expandBuilder_ == null) {
        expand_ = builderForValue.build();
      } else {
        expandBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     */
    public Builder mergeExpand(io.opentdf.platform.policy.policy_common.AttributeExpandSelector value) {
      if (expandBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          expand_ != null &&
          expand_ != io.opentdf.platform.policy.policy_common.AttributeExpandSelector.getDefaultInstance()) {
          getExpandBuilder().mergeFrom(value);
        } else {
          expand_ = value;
        }
      } else {
        expandBuilder_.mergeFrom(value);
      }
      if (expand_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     */
    public Builder clearExpand() {
      bitField0_ = (bitField0_ & ~0x00000002);
      expand_ = null;
      if (expandBuilder_ != null) {
        expandBuilder_.dispose();
        expandBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     */
    public io.opentdf.platform.policy.policy_common.AttributeExpandSelector.Builder getExpandBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getExpandFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     */
    public io.opentdf.platform.policy.policy_common.AttributeExpandSelectorOrBuilder getExpandOrBuilder() {
      if (expandBuilder_ != null) {
        return expandBuilder_.getMessageOrBuilder();
      } else {
        return expand_ == null ?
            io.opentdf.platform.policy.policy_common.AttributeExpandSelector.getDefaultInstance() : expand_;
      }
    }
    /**
     * <pre>
     * Optional expand selector
     * </pre>
     *
     * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentdf.platform.policy.policy_common.AttributeExpandSelector, io.opentdf.platform.policy.policy_common.AttributeExpandSelector.Builder, io.opentdf.platform.policy.policy_common.AttributeExpandSelectorOrBuilder> 
        getExpandFieldBuilder() {
      if (expandBuilder_ == null) {
        expandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opentdf.platform.policy.policy_common.AttributeExpandSelector, io.opentdf.platform.policy.policy_common.AttributeExpandSelector.Builder, io.opentdf.platform.policy.policy_common.AttributeExpandSelectorOrBuilder>(
                getExpand(),
                getParentForChildren(),
                isClean());
        expand_ = null;
      }
      return expandBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:policy.namespaces.GetNamespaceRequest)
  }

  // @@protoc_insertion_point(class_scope:policy.namespaces.GetNamespaceRequest)
  private static final io.opentdf.platform.policy.namespaces.GetNamespaceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.policy.namespaces.GetNamespaceRequest();
  }

  public static io.opentdf.platform.policy.namespaces.GetNamespaceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetNamespaceRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetNamespaceRequest>() {
    @java.lang.Override
    public GetNamespaceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetNamespaceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetNamespaceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.policy.namespaces.GetNamespaceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

