// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/subjectmapping/subject_mapping.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.subjectmapping;

public final class SubjectMappingProto {
  private SubjectMappingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_Condition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_Condition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_ConditionGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_ConditionGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_SubjectSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_SubjectSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_SubjectConditionSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_SubjectConditionSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_SubjectMapping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_SubjectMapping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_Subject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_Subject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_MatchSubjectMappingsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_MatchSubjectMappingsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_MatchSubjectMappingsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_MatchSubjectMappingsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_GetSubjectMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_GetSubjectMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_GetSubjectMappingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_GetSubjectMappingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_ListSubjectMappingsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_ListSubjectMappingsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_ListSubjectMappingsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_ListSubjectMappingsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_CreateSubjectMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_CreateSubjectMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_CreateSubjectMappingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_CreateSubjectMappingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_UpdateSubjectMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_UpdateSubjectMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_UpdateSubjectMappingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_UpdateSubjectMappingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_DeleteSubjectMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_DeleteSubjectMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_DeleteSubjectMappingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_DeleteSubjectMappingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_GetSubjectConditionSetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_GetSubjectConditionSetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_GetSubjectConditionSetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_GetSubjectConditionSetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_ListSubjectConditionSetsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_ListSubjectConditionSetsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_ListSubjectConditionSetsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_ListSubjectConditionSetsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_SubjectConditionSetCreate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_SubjectConditionSetCreate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_CreateSubjectConditionSetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_CreateSubjectConditionSetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_CreateSubjectConditionSetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_CreateSubjectConditionSetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_UpdateSubjectConditionSetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_UpdateSubjectConditionSetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_UpdateSubjectConditionSetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_UpdateSubjectConditionSetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_DeleteSubjectConditionSetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_DeleteSubjectConditionSetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_subjectmapping_DeleteSubjectConditionSetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_subjectmapping_DeleteSubjectConditionSetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+policy/subjectmapping/subject_mapping." +
      "proto\022\025policy.subjectmapping\032!authorizat" +
      "ion/authorization.proto\032\033buf/validate/va" +
      "lidate.proto\032\023common/common.proto\032\034googl" +
      "e/api/annotations.proto\032\034google/protobuf" +
      "/struct.proto\032\"policy/attributes/attribu" +
      "tes.proto\"\325\001\n\tCondition\0224\n\026subject_exter" +
      "nal_field\030\001 \001(\tR\024subjectExternalField\022Z\n" +
      "\010operator\030\002 \001(\01621.policy.subjectmapping." +
      "SubjectMappingOperatorEnumB\013\272H\010\202\001\002\020\001\310\001\001R" +
      "\010operator\0226\n\027subject_external_values\030\003 \003" +
      "(\tR\025subjectExternalValues\"\305\001\n\016ConditionG" +
      "roup\022J\n\nconditions\030\001 \003(\0132 .policy.subjec" +
      "tmapping.ConditionB\010\272H\005\222\001\002\010\001R\nconditions" +
      "\022g\n\020boolean_operator\030\002 \001(\0162/.policy.subj" +
      "ectmapping.ConditionBooleanTypeEnumB\013\272H\010" +
      "\202\001\002\020\001\310\001\001R\017booleanOperator\"h\n\nSubjectSet\022" +
      "Z\n\020condition_groups\030\001 \003(\0132%.policy.subje" +
      "ctmapping.ConditionGroupB\010\272H\005\222\001\002\010\001R\017cond" +
      "itionGroups\"\267\001\n\023SubjectConditionSet\022\016\n\002i" +
      "d\030\001 \001(\tR\002id\022\022\n\004name\030\002 \001(\tR\004name\022,\n\010metad" +
      "ata\030\003 \001(\0132\020.common.MetadataR\010metadata\022N\n" +
      "\014subject_sets\030\004 \003(\0132!.policy.subjectmapp" +
      "ing.SubjectSetB\010\272H\005\222\001\002\010\001R\013subjectSets\"\242\002" +
      "\n\016SubjectMapping\022\016\n\002id\030\001 \001(\tR\002id\022,\n\010meta" +
      "data\030\002 \001(\0132\020.common.MetadataR\010metadata\022A" +
      "\n\017attribute_value\030\003 \001(\0132\030.policy.attribu" +
      "tes.ValueR\016attributeValue\022^\n\025subject_con" +
      "dition_set\030\004 \001(\0132*.policy.subjectmapping" +
      ".SubjectConditionSetR\023subjectConditionSe" +
      "t\022/\n\007actions\030\005 \003(\0132\025.authorization.Actio" +
      "nR\007actions\"B\n\007Subject\0227\n\nattributes\030\001 \001(" +
      "\0132\027.google.protobuf.StructR\nattributes\"W" +
      "\n\033MatchSubjectMappingsRequest\0228\n\007subject" +
      "\030\001 \001(\0132\036.policy.subjectmapping.SubjectR\007" +
      "subject\"p\n\034MatchSubjectMappingsResponse\022" +
      "P\n\020subject_mappings\030\001 \003(\0132%.policy.subje" +
      "ctmapping.SubjectMappingR\017subjectMapping" +
      "s\"2\n\030GetSubjectMappingRequest\022\026\n\002id\030\001 \001(" +
      "\tB\006\272H\003\310\001\001R\002id\"k\n\031GetSubjectMappingRespon" +
      "se\022N\n\017subject_mapping\030\001 \001(\0132%.policy.sub" +
      "jectmapping.SubjectMappingR\016subjectMappi" +
      "ng\"\034\n\032ListSubjectMappingsRequest\"o\n\033List" +
      "SubjectMappingsResponse\022P\n\020subject_mappi" +
      "ngs\030\001 \003(\0132%.policy.subjectmapping.Subjec" +
      "tMappingR\017subjectMappings\"\372\002\n\033CreateSubj" +
      "ectMappingRequest\0223\n\010metadata\030\001 \001(\0132\027.co" +
      "mmon.MetadataMutableR\010metadata\0224\n\022attrib" +
      "ute_value_id\030\002 \001(\tB\006\272H\003\310\001\001R\020attributeVal" +
      "ueId\022H\n!existing_subject_condition_set_i" +
      "d\030\003 \001(\tR\035existingSubjectConditionSetId\022k" +
      "\n\031new_subject_condition_set\030\004 \001(\01320.poli" +
      "cy.subjectmapping.SubjectConditionSetCre" +
      "ateR\026newSubjectConditionSet\0229\n\007actions\030\005" +
      " \003(\0132\025.authorization.ActionB\010\272H\005\222\001\002\010\001R\007a" +
      "ctions\"n\n\034CreateSubjectMappingResponse\022N" +
      "\n\017subject_mapping\030\001 \001(\0132%.policy.subject" +
      "mapping.SubjectMappingR\016subjectMapping\"\373" +
      "\001\n\033UpdateSubjectMappingRequest\022\026\n\002id\030\001 \001" +
      "(\tB\006\272H\003\310\001\001R\002id\022@\n\017update_metadata\030\002 \001(\0132" +
      "\027.common.MetadataMutableR\016updateMetadata" +
      "\022D\n\037update_subject_condition_set_id\030\003 \001(" +
      "\tR\033updateSubjectConditionSetId\022<\n\016update" +
      "_actions\030\005 \003(\0132\025.authorization.ActionR\ru" +
      "pdateActions\"n\n\034UpdateSubjectMappingResp" +
      "onse\022N\n\017subject_mapping\030\001 \001(\0132%.policy.s" +
      "ubjectmapping.SubjectMappingR\016subjectMap" +
      "ping\"5\n\033DeleteSubjectMappingRequest\022\026\n\002i" +
      "d\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"n\n\034DeleteSubjectMapp" +
      "ingResponse\022N\n\017subject_mapping\030\001 \001(\0132%.p" +
      "olicy.subjectmapping.SubjectMappingR\016sub" +
      "jectMapping\"7\n\035GetSubjectConditionSetReq" +
      "uest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"\347\001\n\036GetSubj" +
      "ectConditionSetResponse\022^\n\025subject_condi" +
      "tion_set\030\001 \001(\0132*.policy.subjectmapping.S" +
      "ubjectConditionSetR\023subjectConditionSet\022" +
      "e\n\033associated_subject_mappings\030\002 \003(\0132%.p" +
      "olicy.subjectmapping.SubjectMappingR\031ass" +
      "ociatedSubjectMappings\"!\n\037ListSubjectCon" +
      "ditionSetsRequest\"\204\001\n ListSubjectConditi" +
      "onSetsResponse\022`\n\026subject_condition_sets" +
      "\030\001 \003(\0132*.policy.subjectmapping.SubjectCo" +
      "nditionSetR\024subjectConditionSets\"\240\001\n\031Sub" +
      "jectConditionSetCreate\0223\n\010metadata\030\001 \001(\013" +
      "2\027.common.MetadataMutableR\010metadata\022N\n\014s" +
      "ubject_sets\030\002 \003(\0132!.policy.subjectmappin" +
      "g.SubjectSetB\010\272H\005\222\001\002\010\001R\013subjectSets\"\210\001\n " +
      "CreateSubjectConditionSetRequest\022d\n\025subj" +
      "ect_condition_set\030\001 \001(\01320.policy.subject" +
      "mapping.SubjectConditionSetCreateR\023subje" +
      "ctConditionSet\"3\n!CreateSubjectCondition" +
      "SetResponse\022\016\n\002id\030\001 \001(\tR\002id\"\317\001\n UpdateSu" +
      "bjectConditionSetRequest\022\026\n\002id\030\001 \001(\tB\006\272H" +
      "\003\310\001\001R\002id\022@\n\017update_metadata\030\002 \001(\0132\027.comm" +
      "on.MetadataMutableR\016updateMetadata\022Q\n\023up" +
      "date_subject_sets\030\003 \003(\0132!.policy.subject" +
      "mapping.SubjectSetR\021updateSubjectSets\"3\n" +
      "!UpdateSubjectConditionSetResponse\022\016\n\002id" +
      "\030\001 \001(\tR\002id\":\n DeleteSubjectConditionSetR" +
      "equest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"3\n!Delete" +
      "SubjectConditionSetResponse\022\016\n\002id\030\001 \001(\tR" +
      "\002id*\233\001\n\032SubjectMappingOperatorEnum\022-\n)SU" +
      "BJECT_MAPPING_OPERATOR_ENUM_UNSPECIFIED\020" +
      "\000\022$\n SUBJECT_MAPPING_OPERATOR_ENUM_IN\020\001\022" +
      "(\n$SUBJECT_MAPPING_OPERATOR_ENUM_NOT_IN\020" +
      "\002*\220\001\n\030ConditionBooleanTypeEnum\022+\n\'CONDIT" +
      "ION_BOOLEAN_TYPE_ENUM_UNSPECIFIED\020\000\022#\n\037C" +
      "ONDITION_BOOLEAN_TYPE_ENUM_AND\020\001\022\"\n\036COND" +
      "ITION_BOOLEAN_TYPE_ENUM_OR\020\0022\340\016\n\025Subject" +
      "MappingService\022\251\001\n\024MatchSubjectMappings\022" +
      "2.policy.subjectmapping.MatchSubjectMapp" +
      "ingsRequest\0323.policy.subjectmapping.Matc" +
      "hSubjectMappingsResponse\"(\202\323\344\223\002\"\"\027/subje" +
      "ct-mappings/match:\007subject\022\227\001\n\023ListSubje" +
      "ctMappings\0221.policy.subjectmapping.ListS" +
      "ubjectMappingsRequest\0322.policy.subjectma" +
      "pping.ListSubjectMappingsResponse\"\031\202\323\344\223\002" +
      "\023\022\021/subject-mappings\022\226\001\n\021GetSubjectMappi" +
      "ng\022/.policy.subjectmapping.GetSubjectMap" +
      "pingRequest\0320.policy.subjectmapping.GetS" +
      "ubjectMappingResponse\"\036\202\323\344\223\002\030\022\026/subject-" +
      "mappings/{id}\022\235\001\n\024CreateSubjectMapping\0222" +
      ".policy.subjectmapping.CreateSubjectMapp" +
      "ingRequest\0323.policy.subjectmapping.Creat" +
      "eSubjectMappingResponse\"\034\202\323\344\223\002\026\"\021/subjec" +
      "t-mappings:\001*\022\242\001\n\024UpdateSubjectMapping\0222" +
      ".policy.subjectmapping.UpdateSubjectMapp" +
      "ingRequest\0323.policy.subjectmapping.Updat" +
      "eSubjectMappingResponse\"!\202\323\344\223\002\0332\026/subjec" +
      "t-mappings/{id}:\001*\022\237\001\n\024DeleteSubjectMapp" +
      "ing\0222.policy.subjectmapping.DeleteSubjec" +
      "tMappingRequest\0323.policy.subjectmapping." +
      "DeleteSubjectMappingResponse\"\036\202\323\344\223\002\030*\026/s" +
      "ubject-mappings/{id}\022\254\001\n\030ListSubjectCond" +
      "itionSets\0226.policy.subjectmapping.ListSu" +
      "bjectConditionSetsRequest\0327.policy.subje" +
      "ctmapping.ListSubjectConditionSetsRespon" +
      "se\"\037\202\323\344\223\002\031\022\027/subject-condition-sets\022\253\001\n\026" +
      "GetSubjectConditionSet\0224.policy.subjectm" +
      "apping.GetSubjectConditionSetRequest\0325.p" +
      "olicy.subjectmapping.GetSubjectCondition" +
      "SetResponse\"$\202\323\344\223\002\036\022\034/subject-condition-" +
      "sets/{id}\022\262\001\n\031CreateSubjectConditionSet\022" +
      "7.policy.subjectmapping.CreateSubjectCon" +
      "ditionSetRequest\0328.policy.subjectmapping" +
      ".CreateSubjectConditionSetResponse\"\"\202\323\344\223" +
      "\002\034\"\027/subject-condition-sets:\001*\022\267\001\n\031Updat" +
      "eSubjectConditionSet\0227.policy.subjectmap" +
      "ping.UpdateSubjectConditionSetRequest\0328." +
      "policy.subjectmapping.UpdateSubjectCondi" +
      "tionSetResponse\"\'\202\323\344\223\002!2\034/subject-condit" +
      "ion-sets/{id}:\001*\022\264\001\n\031DeleteSubjectCondit" +
      "ionSet\0227.policy.subjectmapping.DeleteSub" +
      "jectConditionSetRequest\0328.policy.subject" +
      "mapping.DeleteSubjectConditionSetRespons" +
      "e\"$\202\323\344\223\002\036*\034/subject-condition-sets/{id}B" +
      "\364\001\n)io.opentdf.platform.policy.subjectma" +
      "ppingB\023SubjectMappingProtoP\001Z=github.com" +
      "/opentdf/platform/protocol/go/policy/sub" +
      "jectmapping\242\002\003PSX\252\002\025Policy.Subjectmappin" +
      "g\312\002\025Policy\\Subjectmapping\342\002!Policy\\Subje" +
      "ctmapping\\GPBMetadata\352\002\026Policy::Subjectm" +
      "appingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.opentdf.platform.authorization.AuthorizationProto.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
          io.opentdf.platform.common.CommonProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          io.opentdf.platform.policy.attributes.AttributesProto.getDescriptor(),
        });
    internal_static_policy_subjectmapping_Condition_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_policy_subjectmapping_Condition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_Condition_descriptor,
        new java.lang.String[] { "SubjectExternalField", "Operator", "SubjectExternalValues", });
    internal_static_policy_subjectmapping_ConditionGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_policy_subjectmapping_ConditionGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_ConditionGroup_descriptor,
        new java.lang.String[] { "Conditions", "BooleanOperator", });
    internal_static_policy_subjectmapping_SubjectSet_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_policy_subjectmapping_SubjectSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_SubjectSet_descriptor,
        new java.lang.String[] { "ConditionGroups", });
    internal_static_policy_subjectmapping_SubjectConditionSet_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_policy_subjectmapping_SubjectConditionSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_SubjectConditionSet_descriptor,
        new java.lang.String[] { "Id", "Name", "Metadata", "SubjectSets", });
    internal_static_policy_subjectmapping_SubjectMapping_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_policy_subjectmapping_SubjectMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_SubjectMapping_descriptor,
        new java.lang.String[] { "Id", "Metadata", "AttributeValue", "SubjectConditionSet", "Actions", });
    internal_static_policy_subjectmapping_Subject_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_policy_subjectmapping_Subject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_Subject_descriptor,
        new java.lang.String[] { "Attributes", });
    internal_static_policy_subjectmapping_MatchSubjectMappingsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_policy_subjectmapping_MatchSubjectMappingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_MatchSubjectMappingsRequest_descriptor,
        new java.lang.String[] { "Subject", });
    internal_static_policy_subjectmapping_MatchSubjectMappingsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_policy_subjectmapping_MatchSubjectMappingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_MatchSubjectMappingsResponse_descriptor,
        new java.lang.String[] { "SubjectMappings", });
    internal_static_policy_subjectmapping_GetSubjectMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_policy_subjectmapping_GetSubjectMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_GetSubjectMappingRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_subjectmapping_GetSubjectMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_policy_subjectmapping_GetSubjectMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_GetSubjectMappingResponse_descriptor,
        new java.lang.String[] { "SubjectMapping", });
    internal_static_policy_subjectmapping_ListSubjectMappingsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_policy_subjectmapping_ListSubjectMappingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_ListSubjectMappingsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_policy_subjectmapping_ListSubjectMappingsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_policy_subjectmapping_ListSubjectMappingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_ListSubjectMappingsResponse_descriptor,
        new java.lang.String[] { "SubjectMappings", });
    internal_static_policy_subjectmapping_CreateSubjectMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_policy_subjectmapping_CreateSubjectMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_CreateSubjectMappingRequest_descriptor,
        new java.lang.String[] { "Metadata", "AttributeValueId", "ExistingSubjectConditionSetId", "NewSubjectConditionSet", "Actions", });
    internal_static_policy_subjectmapping_CreateSubjectMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_policy_subjectmapping_CreateSubjectMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_CreateSubjectMappingResponse_descriptor,
        new java.lang.String[] { "SubjectMapping", });
    internal_static_policy_subjectmapping_UpdateSubjectMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_policy_subjectmapping_UpdateSubjectMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_UpdateSubjectMappingRequest_descriptor,
        new java.lang.String[] { "Id", "UpdateMetadata", "UpdateSubjectConditionSetId", "UpdateActions", });
    internal_static_policy_subjectmapping_UpdateSubjectMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_policy_subjectmapping_UpdateSubjectMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_UpdateSubjectMappingResponse_descriptor,
        new java.lang.String[] { "SubjectMapping", });
    internal_static_policy_subjectmapping_DeleteSubjectMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_policy_subjectmapping_DeleteSubjectMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_DeleteSubjectMappingRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_subjectmapping_DeleteSubjectMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_policy_subjectmapping_DeleteSubjectMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_DeleteSubjectMappingResponse_descriptor,
        new java.lang.String[] { "SubjectMapping", });
    internal_static_policy_subjectmapping_GetSubjectConditionSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_policy_subjectmapping_GetSubjectConditionSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_GetSubjectConditionSetRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_subjectmapping_GetSubjectConditionSetResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_policy_subjectmapping_GetSubjectConditionSetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_GetSubjectConditionSetResponse_descriptor,
        new java.lang.String[] { "SubjectConditionSet", "AssociatedSubjectMappings", });
    internal_static_policy_subjectmapping_ListSubjectConditionSetsRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_policy_subjectmapping_ListSubjectConditionSetsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_ListSubjectConditionSetsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_policy_subjectmapping_ListSubjectConditionSetsResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_policy_subjectmapping_ListSubjectConditionSetsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_ListSubjectConditionSetsResponse_descriptor,
        new java.lang.String[] { "SubjectConditionSets", });
    internal_static_policy_subjectmapping_SubjectConditionSetCreate_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_policy_subjectmapping_SubjectConditionSetCreate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_SubjectConditionSetCreate_descriptor,
        new java.lang.String[] { "Metadata", "SubjectSets", });
    internal_static_policy_subjectmapping_CreateSubjectConditionSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_policy_subjectmapping_CreateSubjectConditionSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_CreateSubjectConditionSetRequest_descriptor,
        new java.lang.String[] { "SubjectConditionSet", });
    internal_static_policy_subjectmapping_CreateSubjectConditionSetResponse_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_policy_subjectmapping_CreateSubjectConditionSetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_CreateSubjectConditionSetResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_subjectmapping_UpdateSubjectConditionSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_policy_subjectmapping_UpdateSubjectConditionSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_UpdateSubjectConditionSetRequest_descriptor,
        new java.lang.String[] { "Id", "UpdateMetadata", "UpdateSubjectSets", });
    internal_static_policy_subjectmapping_UpdateSubjectConditionSetResponse_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_policy_subjectmapping_UpdateSubjectConditionSetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_UpdateSubjectConditionSetResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_subjectmapping_DeleteSubjectConditionSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_policy_subjectmapping_DeleteSubjectConditionSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_DeleteSubjectConditionSetRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_subjectmapping_DeleteSubjectConditionSetResponse_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_policy_subjectmapping_DeleteSubjectConditionSetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_subjectmapping_DeleteSubjectConditionSetResponse_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    io.opentdf.platform.authorization.AuthorizationProto.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    io.opentdf.platform.common.CommonProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    io.opentdf.platform.policy.attributes.AttributesProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
