// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: policy/actions/actions.proto

package actionsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	actions "github.com/opentdf/platform/protocol/go/policy/actions"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ActionServiceName is the fully-qualified name of the ActionService service.
	ActionServiceName = "policy.actions.ActionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ActionServiceGetActionProcedure is the fully-qualified name of the ActionService's GetAction RPC.
	ActionServiceGetActionProcedure = "/policy.actions.ActionService/GetAction"
	// ActionServiceListActionsProcedure is the fully-qualified name of the ActionService's ListActions
	// RPC.
	ActionServiceListActionsProcedure = "/policy.actions.ActionService/ListActions"
	// ActionServiceCreateCustomActionProcedure is the fully-qualified name of the ActionService's
	// CreateCustomAction RPC.
	ActionServiceCreateCustomActionProcedure = "/policy.actions.ActionService/CreateCustomAction"
	// ActionServiceUpdateActionProcedure is the fully-qualified name of the ActionService's
	// UpdateAction RPC.
	ActionServiceUpdateActionProcedure = "/policy.actions.ActionService/UpdateAction"
	// ActionServiceDeleteCustomActionProcedure is the fully-qualified name of the ActionService's
	// DeleteCustomAction RPC.
	ActionServiceDeleteCustomActionProcedure = "/policy.actions.ActionService/DeleteCustomAction"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	actionServiceServiceDescriptor                  = actions.File_policy_actions_actions_proto.Services().ByName("ActionService")
	actionServiceGetActionMethodDescriptor          = actionServiceServiceDescriptor.Methods().ByName("GetAction")
	actionServiceListActionsMethodDescriptor        = actionServiceServiceDescriptor.Methods().ByName("ListActions")
	actionServiceCreateCustomActionMethodDescriptor = actionServiceServiceDescriptor.Methods().ByName("CreateCustomAction")
	actionServiceUpdateActionMethodDescriptor       = actionServiceServiceDescriptor.Methods().ByName("UpdateAction")
	actionServiceDeleteCustomActionMethodDescriptor = actionServiceServiceDescriptor.Methods().ByName("DeleteCustomAction")
)

// ActionServiceClient is a client for the policy.actions.ActionService service.
type ActionServiceClient interface {
	GetAction(context.Context, *connect.Request[actions.GetActionRequest]) (*connect.Response[actions.GetActionResponse], error)
	ListActions(context.Context, *connect.Request[actions.ListActionsRequest]) (*connect.Response[actions.ListActionsResponse], error)
	CreateCustomAction(context.Context, *connect.Request[actions.CreateCustomActionRequest]) (*connect.Response[actions.CreateCustomActionResponse], error)
	UpdateAction(context.Context, *connect.Request[actions.UpdateActionRequest]) (*connect.Response[actions.UpdateActionResponse], error)
	DeleteCustomAction(context.Context, *connect.Request[actions.DeleteCustomActionRequest]) (*connect.Response[actions.DeleteCustomActionResponse], error)
}

// NewActionServiceClient constructs a client for the policy.actions.ActionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewActionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ActionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &actionServiceClient{
		getAction: connect.NewClient[actions.GetActionRequest, actions.GetActionResponse](
			httpClient,
			baseURL+ActionServiceGetActionProcedure,
			connect.WithSchema(actionServiceGetActionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listActions: connect.NewClient[actions.ListActionsRequest, actions.ListActionsResponse](
			httpClient,
			baseURL+ActionServiceListActionsProcedure,
			connect.WithSchema(actionServiceListActionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createCustomAction: connect.NewClient[actions.CreateCustomActionRequest, actions.CreateCustomActionResponse](
			httpClient,
			baseURL+ActionServiceCreateCustomActionProcedure,
			connect.WithSchema(actionServiceCreateCustomActionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateAction: connect.NewClient[actions.UpdateActionRequest, actions.UpdateActionResponse](
			httpClient,
			baseURL+ActionServiceUpdateActionProcedure,
			connect.WithSchema(actionServiceUpdateActionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteCustomAction: connect.NewClient[actions.DeleteCustomActionRequest, actions.DeleteCustomActionResponse](
			httpClient,
			baseURL+ActionServiceDeleteCustomActionProcedure,
			connect.WithSchema(actionServiceDeleteCustomActionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// actionServiceClient implements ActionServiceClient.
type actionServiceClient struct {
	getAction          *connect.Client[actions.GetActionRequest, actions.GetActionResponse]
	listActions        *connect.Client[actions.ListActionsRequest, actions.ListActionsResponse]
	createCustomAction *connect.Client[actions.CreateCustomActionRequest, actions.CreateCustomActionResponse]
	updateAction       *connect.Client[actions.UpdateActionRequest, actions.UpdateActionResponse]
	deleteCustomAction *connect.Client[actions.DeleteCustomActionRequest, actions.DeleteCustomActionResponse]
}

// GetAction calls policy.actions.ActionService.GetAction.
func (c *actionServiceClient) GetAction(ctx context.Context, req *connect.Request[actions.GetActionRequest]) (*connect.Response[actions.GetActionResponse], error) {
	return c.getAction.CallUnary(ctx, req)
}

// ListActions calls policy.actions.ActionService.ListActions.
func (c *actionServiceClient) ListActions(ctx context.Context, req *connect.Request[actions.ListActionsRequest]) (*connect.Response[actions.ListActionsResponse], error) {
	return c.listActions.CallUnary(ctx, req)
}

// CreateCustomAction calls policy.actions.ActionService.CreateCustomAction.
func (c *actionServiceClient) CreateCustomAction(ctx context.Context, req *connect.Request[actions.CreateCustomActionRequest]) (*connect.Response[actions.CreateCustomActionResponse], error) {
	return c.createCustomAction.CallUnary(ctx, req)
}

// UpdateAction calls policy.actions.ActionService.UpdateAction.
func (c *actionServiceClient) UpdateAction(ctx context.Context, req *connect.Request[actions.UpdateActionRequest]) (*connect.Response[actions.UpdateActionResponse], error) {
	return c.updateAction.CallUnary(ctx, req)
}

// DeleteCustomAction calls policy.actions.ActionService.DeleteCustomAction.
func (c *actionServiceClient) DeleteCustomAction(ctx context.Context, req *connect.Request[actions.DeleteCustomActionRequest]) (*connect.Response[actions.DeleteCustomActionResponse], error) {
	return c.deleteCustomAction.CallUnary(ctx, req)
}

// ActionServiceHandler is an implementation of the policy.actions.ActionService service.
type ActionServiceHandler interface {
	GetAction(context.Context, *connect.Request[actions.GetActionRequest]) (*connect.Response[actions.GetActionResponse], error)
	ListActions(context.Context, *connect.Request[actions.ListActionsRequest]) (*connect.Response[actions.ListActionsResponse], error)
	CreateCustomAction(context.Context, *connect.Request[actions.CreateCustomActionRequest]) (*connect.Response[actions.CreateCustomActionResponse], error)
	UpdateAction(context.Context, *connect.Request[actions.UpdateActionRequest]) (*connect.Response[actions.UpdateActionResponse], error)
	DeleteCustomAction(context.Context, *connect.Request[actions.DeleteCustomActionRequest]) (*connect.Response[actions.DeleteCustomActionResponse], error)
}

// NewActionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewActionServiceHandler(svc ActionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	actionServiceGetActionHandler := connect.NewUnaryHandler(
		ActionServiceGetActionProcedure,
		svc.GetAction,
		connect.WithSchema(actionServiceGetActionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceListActionsHandler := connect.NewUnaryHandler(
		ActionServiceListActionsProcedure,
		svc.ListActions,
		connect.WithSchema(actionServiceListActionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceCreateCustomActionHandler := connect.NewUnaryHandler(
		ActionServiceCreateCustomActionProcedure,
		svc.CreateCustomAction,
		connect.WithSchema(actionServiceCreateCustomActionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceUpdateActionHandler := connect.NewUnaryHandler(
		ActionServiceUpdateActionProcedure,
		svc.UpdateAction,
		connect.WithSchema(actionServiceUpdateActionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	actionServiceDeleteCustomActionHandler := connect.NewUnaryHandler(
		ActionServiceDeleteCustomActionProcedure,
		svc.DeleteCustomAction,
		connect.WithSchema(actionServiceDeleteCustomActionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/policy.actions.ActionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ActionServiceGetActionProcedure:
			actionServiceGetActionHandler.ServeHTTP(w, r)
		case ActionServiceListActionsProcedure:
			actionServiceListActionsHandler.ServeHTTP(w, r)
		case ActionServiceCreateCustomActionProcedure:
			actionServiceCreateCustomActionHandler.ServeHTTP(w, r)
		case ActionServiceUpdateActionProcedure:
			actionServiceUpdateActionHandler.ServeHTTP(w, r)
		case ActionServiceDeleteCustomActionProcedure:
			actionServiceDeleteCustomActionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedActionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedActionServiceHandler struct{}

func (UnimplementedActionServiceHandler) GetAction(context.Context, *connect.Request[actions.GetActionRequest]) (*connect.Response[actions.GetActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("policy.actions.ActionService.GetAction is not implemented"))
}

func (UnimplementedActionServiceHandler) ListActions(context.Context, *connect.Request[actions.ListActionsRequest]) (*connect.Response[actions.ListActionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("policy.actions.ActionService.ListActions is not implemented"))
}

func (UnimplementedActionServiceHandler) CreateCustomAction(context.Context, *connect.Request[actions.CreateCustomActionRequest]) (*connect.Response[actions.CreateCustomActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("policy.actions.ActionService.CreateCustomAction is not implemented"))
}

func (UnimplementedActionServiceHandler) UpdateAction(context.Context, *connect.Request[actions.UpdateActionRequest]) (*connect.Response[actions.UpdateActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("policy.actions.ActionService.UpdateAction is not implemented"))
}

func (UnimplementedActionServiceHandler) DeleteCustomAction(context.Context, *connect.Request[actions.DeleteCustomActionRequest]) (*connect.Response[actions.DeleteCustomActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("policy.actions.ActionService.DeleteCustomAction is not implemented"))
}
