// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/entity.proto

// Protobuf Java Version: 3.25.3
package com.entity;

public interface EntityCustomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:entity.EntityCustom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any extension = 1 [json_name = "extension"];</code>
   * @return Whether the extension field is set.
   */
  boolean hasExtension();
  /**
   * <code>.google.protobuf.Any extension = 1 [json_name = "extension"];</code>
   * @return The extension.
   */
  com.google.protobuf.Any getExtension();
  /**
   * <code>.google.protobuf.Any extension = 1 [json_name = "extension"];</code>
   */
  com.google.protobuf.AnyOrBuilder getExtensionOrBuilder();
}
