// @generated by protoc-gen-es v2.2.1
// @generated from file kas/kas.proto (package kas, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { StringValueSchema, Value } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file kas/kas.proto.
 */
export declare const file_kas_kas: GenFile;

/**
 * Intentionally empty. May include features later.
 *
 * @generated from message kas.InfoRequest
 */
export declare type InfoRequest = Message<"kas.InfoRequest"> & {
};

/**
 * Describes the message kas.InfoRequest.
 * Use `create(InfoRequestSchema)` to create a new message.
 */
export declare const InfoRequestSchema: GenMessage<InfoRequest>;

/**
 * Service application level metadata
 *
 * @generated from message kas.InfoResponse
 */
export declare type InfoResponse = Message<"kas.InfoResponse"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;
};

/**
 * Describes the message kas.InfoResponse.
 * Use `create(InfoResponseSchema)` to create a new message.
 */
export declare const InfoResponseSchema: GenMessage<InfoResponse>;

/**
 * @generated from message kas.LegacyPublicKeyRequest
 */
export declare type LegacyPublicKeyRequest = Message<"kas.LegacyPublicKeyRequest"> & {
  /**
   * @generated from field: string algorithm = 1;
   */
  algorithm: string;
};

/**
 * Describes the message kas.LegacyPublicKeyRequest.
 * Use `create(LegacyPublicKeyRequestSchema)` to create a new message.
 */
export declare const LegacyPublicKeyRequestSchema: GenMessage<LegacyPublicKeyRequest>;

/**
 * @generated from message kas.PublicKeyRequest
 */
export declare type PublicKeyRequest = Message<"kas.PublicKeyRequest"> & {
  /**
   * @generated from field: string algorithm = 1;
   */
  algorithm: string;

  /**
   * @generated from field: string fmt = 2;
   */
  fmt: string;

  /**
   * @generated from field: string v = 3;
   */
  v: string;
};

/**
 * Describes the message kas.PublicKeyRequest.
 * Use `create(PublicKeyRequestSchema)` to create a new message.
 */
export declare const PublicKeyRequestSchema: GenMessage<PublicKeyRequest>;

/**
 * @generated from message kas.PublicKeyResponse
 */
export declare type PublicKeyResponse = Message<"kas.PublicKeyResponse"> & {
  /**
   * @generated from field: string public_key = 1;
   */
  publicKey: string;

  /**
   * @generated from field: string kid = 2;
   */
  kid: string;
};

/**
 * Describes the message kas.PublicKeyResponse.
 * Use `create(PublicKeyResponseSchema)` to create a new message.
 */
export declare const PublicKeyResponseSchema: GenMessage<PublicKeyResponse>;

/**
 * @generated from message kas.RewrapRequest
 */
export declare type RewrapRequest = Message<"kas.RewrapRequest"> & {
  /**
   * @generated from field: string signed_request_token = 1;
   */
  signedRequestToken: string;
};

/**
 * Describes the message kas.RewrapRequest.
 * Use `create(RewrapRequestSchema)` to create a new message.
 */
export declare const RewrapRequestSchema: GenMessage<RewrapRequest>;

/**
 * @generated from message kas.RewrapResponse
 */
export declare type RewrapResponse = Message<"kas.RewrapResponse"> & {
  /**
   * @generated from field: map<string, google.protobuf.Value> metadata = 1;
   */
  metadata: { [key: string]: Value };

  /**
   * @generated from field: bytes entity_wrapped_key = 2;
   */
  entityWrappedKey: Uint8Array;

  /**
   * @generated from field: string session_public_key = 3;
   */
  sessionPublicKey: string;

  /**
   * @generated from field: string schema_version = 4;
   */
  schemaVersion: string;
};

/**
 * Describes the message kas.RewrapResponse.
 * Use `create(RewrapResponseSchema)` to create a new message.
 */
export declare const RewrapResponseSchema: GenMessage<RewrapResponse>;

/**
 * Get app info from the root path
 *
 * @generated from service kas.AccessService
 */
export declare const AccessService: GenService<{
  /**
   * @generated from rpc kas.AccessService.PublicKey
   */
  publicKey: {
    methodKind: "unary";
    input: typeof PublicKeyRequestSchema;
    output: typeof PublicKeyResponseSchema;
  },
  /**
   * buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
   *
   * @generated from rpc kas.AccessService.LegacyPublicKey
   */
  legacyPublicKey: {
    methodKind: "unary";
    input: typeof LegacyPublicKeyRequestSchema;
    output: typeof StringValueSchema;
  },
  /**
   * @generated from rpc kas.AccessService.Rewrap
   */
  rewrap: {
    methodKind: "unary";
    input: typeof RewrapRequestSchema;
    output: typeof RewrapResponseSchema;
  },
}>;

