// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/attributes/attributes.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.attributes;

public interface GetAttributesByValueFqnsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.attributes.GetAttributesByValueFqnsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string fqns = 1 [json_name = "fqns", (.buf.validate.field) = { ... }</code>
   * @return A list containing the fqns.
   */
  java.util.List<java.lang.String>
      getFqnsList();
  /**
   * <code>repeated string fqns = 1 [json_name = "fqns", (.buf.validate.field) = { ... }</code>
   * @return The count of fqns.
   */
  int getFqnsCount();
  /**
   * <code>repeated string fqns = 1 [json_name = "fqns", (.buf.validate.field) = { ... }</code>
   * @param index The index of the element to return.
   * @return The fqns at the given index.
   */
  java.lang.String getFqns(int index);
  /**
   * <code>repeated string fqns = 1 [json_name = "fqns", (.buf.validate.field) = { ... }</code>
   * @param index The index of the value to return.
   * @return The bytes of the fqns at the given index.
   */
  com.google.protobuf.ByteString
      getFqnsBytes(int index);

  /**
   * <pre>
   * Optional expand selector
   * </pre>
   *
   * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
   * @return Whether the expand field is set.
   */
  boolean hasExpand();
  /**
   * <pre>
   * Optional expand selector
   * </pre>
   *
   * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
   * @return The expand.
   */
  io.opentdf.platform.policy.policy_common.AttributeExpandSelector getExpand();
  /**
   * <pre>
   * Optional expand selector
   * </pre>
   *
   * <code>.policy.policy_common.AttributeExpandSelector expand = 2 [json_name = "expand"];</code>
   */
  io.opentdf.platform.policy.policy_common.AttributeExpandSelectorOrBuilder getExpandOrBuilder();
}
