// Command codegen copies helper source files from protocol/go/helpers/ into their
// corresponding proto package directories with a "Code generated" header prepended.
// Helper source files import proto types explicitly for IDE support; the copier strips
// the self-referencing import and type qualifiers so the output compiles in-package.
//
// See ADR DSPX-2594 for background on the source-file codegen approach.
package main

import (
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

// helperMapping defines a source directory (relative to protocol/go/helpers/) and its
// target directory (relative to protocol/go/) where files will be copied.
type helperMapping struct {
	// Source is the subdirectory under helpers/ containing the source files.
	Source string
	// Target is the subdirectory under protocol/go/ where files are copied.
	Target string
	// ProtoImportPath is the full Go import path of the target proto package.
	ProtoImportPath string
	// ProtoImportAlias is the import alias used in the source files for the proto package.
	ProtoImportAlias string
}

var mappings = []helperMapping{
	{
		Source:           "authorization/v2",
		Target:           "authorization/v2",
		ProtoImportPath:  "github.com/opentdf/platform/protocol/go/authorization/v2",
		ProtoImportAlias: "authorizationv2",
	},
}

const generatedHeader = "// Code generated by protocol/go/codegen. DO NOT EDIT.\n\n"

func main() {
	baseDir, err := getBaseDir()
	if err != nil {
		log.Fatal(err)
	}

	helpersDir := filepath.Join(baseDir, "helpers")
	for _, m := range mappings {
		srcDir := filepath.Join(helpersDir, m.Source)
		dstDir := filepath.Join(baseDir, m.Target)
		if err := copyHelpers(srcDir, dstDir, m); err != nil {
			log.Fatalf("copying helpers from %s to %s: %v", srcDir, dstDir, err)
		}
	}
}

func copyHelpers(srcDir, dstDir string, m helperMapping) error {
	// Remove stale .gen.go files so that renamed or deleted helpers don't linger.
	if err := removeGenFiles(dstDir); err != nil {
		return fmt.Errorf("cleaning target directory: %w", err)
	}

	entries, err := os.ReadDir(srcDir)
	if err != nil {
		return fmt.Errorf("reading source directory: %w", err)
	}

	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}

		src := filepath.Join(srcDir, name)
		content, err := os.ReadFile(src)
		if err != nil {
			return fmt.Errorf("reading %s: %w", src, err)
		}

		transformed := rewriteImports(string(content), m)

		outName := strings.TrimSuffix(name, ".go") + ".gen.go"
		dst := filepath.Join(dstDir, outName)

		output := generatedHeader + transformed
		if err := os.WriteFile(dst, []byte(output), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", dst, err)
		}
		fmt.Printf("  %s -> %s\n", src, dst)
	}
	return nil
}

func removeGenFiles(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("reading directory: %w", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".gen.go") {
			if err := os.Remove(filepath.Join(dir, entry.Name())); err != nil {
				return fmt.Errorf("removing %s: %w", entry.Name(), err)
			}
		}
	}
	return nil
}

// rewriteImports removes the self-referencing proto import and strips the alias qualifier
// from type references so the file compiles inside the proto package.
//
// The qualifier regex also matches inside string literals and comments. This is acceptable
// because we control the source files and don't use the alias in non-code contexts.
func rewriteImports(content string, m helperMapping) string {
	// Remove the import line: `authorizationv2 "github.com/.../authorization/v2"`
	importLineRe := regexp.MustCompile(
		`(?m)^\s*` + regexp.QuoteMeta(m.ProtoImportAlias) + `\s+"` + regexp.QuoteMeta(m.ProtoImportPath) + `"\s*\n`,
	)
	content = importLineRe.ReplaceAllString(content, "")

	// Strip the alias qualifier from type references: `authorizationv2.Foo` -> `Foo`
	qualifierRe := regexp.MustCompile(regexp.QuoteMeta(m.ProtoImportAlias) + `\.`)
	content = qualifierRe.ReplaceAllString(content, "")

	return content
}

// getBaseDir returns the protocol/go/ directory by navigating from this file's location.
func getBaseDir() (string, error) {
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		return "", errors.New("could not determine current file location")
	}
	return filepath.Dir(filepath.Dir(filename)), nil
}
