FROM wiremock/wiremock:latest

RUN curl https://repo1.maven.org/maven2/org/wiremock/wiremock-grpc-extension-standalone/0.4.0/wiremock-grpc-extension-standalone-0.4.0.jar \
    -o /var/wiremock/extensions/wiremock-grpc-extension-standalone.jar