// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentdf/platform/resourcemapping/resource_mapping.proto

// Protobuf Java Version: 3.25.2
package io.opentdf.platform.resourcemapping;

public interface ListResourceMappingsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:opentdf.platform.resourcemapping.ListResourceMappingsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .opentdf.platform.resourcemapping.ResourceMapping resource_mappings = 1 [json_name = "resourceMappings"];</code>
   */
  java.util.List<io.opentdf.platform.resourcemapping.ResourceMapping> 
      getResourceMappingsList();
  /**
   * <code>repeated .opentdf.platform.resourcemapping.ResourceMapping resource_mappings = 1 [json_name = "resourceMappings"];</code>
   */
  io.opentdf.platform.resourcemapping.ResourceMapping getResourceMappings(int index);
  /**
   * <code>repeated .opentdf.platform.resourcemapping.ResourceMapping resource_mappings = 1 [json_name = "resourceMappings"];</code>
   */
  int getResourceMappingsCount();
  /**
   * <code>repeated .opentdf.platform.resourcemapping.ResourceMapping resource_mappings = 1 [json_name = "resourceMappings"];</code>
   */
  java.util.List<? extends io.opentdf.platform.resourcemapping.ResourceMappingOrBuilder> 
      getResourceMappingsOrBuilderList();
  /**
   * <code>repeated .opentdf.platform.resourcemapping.ResourceMapping resource_mappings = 1 [json_name = "resourceMappings"];</code>
   */
  io.opentdf.platform.resourcemapping.ResourceMappingOrBuilder getResourceMappingsOrBuilder(
      int index);
}
