// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: access/access.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.access;

/**
 * Protobuf type {@code access.RewrapRequest}
 */
public final class RewrapRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:access.RewrapRequest)
    RewrapRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RewrapRequest.newBuilder() to construct.
  private RewrapRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RewrapRequest() {
    signedRequestToken_ = "";
    bearer_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RewrapRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.access.AccessProto.internal_static_access_RewrapRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.access.AccessProto.internal_static_access_RewrapRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.access.RewrapRequest.class, io.opentdf.platform.access.RewrapRequest.Builder.class);
  }

  public static final int SIGNED_REQUEST_TOKEN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object signedRequestToken_ = "";
  /**
   * <code>string signed_request_token = 1 [json_name = "signedRequestToken"];</code>
   * @return The signedRequestToken.
   */
  @java.lang.Override
  public java.lang.String getSignedRequestToken() {
    java.lang.Object ref = signedRequestToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signedRequestToken_ = s;
      return s;
    }
  }
  /**
   * <code>string signed_request_token = 1 [json_name = "signedRequestToken"];</code>
   * @return The bytes for signedRequestToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSignedRequestTokenBytes() {
    java.lang.Object ref = signedRequestToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signedRequestToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BEARER_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bearer_ = "";
  /**
   * <code>string bearer = 2 [json_name = "bearer"];</code>
   * @return The bearer.
   */
  @java.lang.Override
  public java.lang.String getBearer() {
    java.lang.Object ref = bearer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bearer_ = s;
      return s;
    }
  }
  /**
   * <code>string bearer = 2 [json_name = "bearer"];</code>
   * @return The bytes for bearer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBearerBytes() {
    java.lang.Object ref = bearer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bearer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signedRequestToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, signedRequestToken_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bearer_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bearer_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signedRequestToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, signedRequestToken_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bearer_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bearer_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.access.RewrapRequest)) {
      return super.equals(obj);
    }
    io.opentdf.platform.access.RewrapRequest other = (io.opentdf.platform.access.RewrapRequest) obj;

    if (!getSignedRequestToken()
        .equals(other.getSignedRequestToken())) return false;
    if (!getBearer()
        .equals(other.getBearer())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIGNED_REQUEST_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getSignedRequestToken().hashCode();
    hash = (37 * hash) + BEARER_FIELD_NUMBER;
    hash = (53 * hash) + getBearer().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.access.RewrapRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.access.RewrapRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.access.RewrapRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.access.RewrapRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.access.RewrapRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code access.RewrapRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:access.RewrapRequest)
      io.opentdf.platform.access.RewrapRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.access.AccessProto.internal_static_access_RewrapRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.access.AccessProto.internal_static_access_RewrapRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.access.RewrapRequest.class, io.opentdf.platform.access.RewrapRequest.Builder.class);
    }

    // Construct using io.opentdf.platform.access.RewrapRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      signedRequestToken_ = "";
      bearer_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.access.AccessProto.internal_static_access_RewrapRequest_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.access.RewrapRequest getDefaultInstanceForType() {
      return io.opentdf.platform.access.RewrapRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.access.RewrapRequest build() {
      io.opentdf.platform.access.RewrapRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.access.RewrapRequest buildPartial() {
      io.opentdf.platform.access.RewrapRequest result = new io.opentdf.platform.access.RewrapRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentdf.platform.access.RewrapRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.signedRequestToken_ = signedRequestToken_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bearer_ = bearer_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.access.RewrapRequest) {
        return mergeFrom((io.opentdf.platform.access.RewrapRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.access.RewrapRequest other) {
      if (other == io.opentdf.platform.access.RewrapRequest.getDefaultInstance()) return this;
      if (!other.getSignedRequestToken().isEmpty()) {
        signedRequestToken_ = other.signedRequestToken_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getBearer().isEmpty()) {
        bearer_ = other.bearer_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              signedRequestToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              bearer_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object signedRequestToken_ = "";
    /**
     * <code>string signed_request_token = 1 [json_name = "signedRequestToken"];</code>
     * @return The signedRequestToken.
     */
    public java.lang.String getSignedRequestToken() {
      java.lang.Object ref = signedRequestToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signedRequestToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string signed_request_token = 1 [json_name = "signedRequestToken"];</code>
     * @return The bytes for signedRequestToken.
     */
    public com.google.protobuf.ByteString
        getSignedRequestTokenBytes() {
      java.lang.Object ref = signedRequestToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signedRequestToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string signed_request_token = 1 [json_name = "signedRequestToken"];</code>
     * @param value The signedRequestToken to set.
     * @return This builder for chaining.
     */
    public Builder setSignedRequestToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      signedRequestToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string signed_request_token = 1 [json_name = "signedRequestToken"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSignedRequestToken() {
      signedRequestToken_ = getDefaultInstance().getSignedRequestToken();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string signed_request_token = 1 [json_name = "signedRequestToken"];</code>
     * @param value The bytes for signedRequestToken to set.
     * @return This builder for chaining.
     */
    public Builder setSignedRequestTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      signedRequestToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object bearer_ = "";
    /**
     * <code>string bearer = 2 [json_name = "bearer"];</code>
     * @return The bearer.
     */
    public java.lang.String getBearer() {
      java.lang.Object ref = bearer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bearer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bearer = 2 [json_name = "bearer"];</code>
     * @return The bytes for bearer.
     */
    public com.google.protobuf.ByteString
        getBearerBytes() {
      java.lang.Object ref = bearer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bearer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bearer = 2 [json_name = "bearer"];</code>
     * @param value The bearer to set.
     * @return This builder for chaining.
     */
    public Builder setBearer(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bearer_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string bearer = 2 [json_name = "bearer"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBearer() {
      bearer_ = getDefaultInstance().getBearer();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string bearer = 2 [json_name = "bearer"];</code>
     * @param value The bytes for bearer to set.
     * @return This builder for chaining.
     */
    public Builder setBearerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bearer_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:access.RewrapRequest)
  }

  // @@protoc_insertion_point(class_scope:access.RewrapRequest)
  private static final io.opentdf.platform.access.RewrapRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.access.RewrapRequest();
  }

  public static io.opentdf.platform.access.RewrapRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RewrapRequest>
      PARSER = new com.google.protobuf.AbstractParser<RewrapRequest>() {
    @java.lang.Override
    public RewrapRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RewrapRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RewrapRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.access.RewrapRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

