// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subjectmapping/subject_mapping.proto

// Protobuf Java Version: 3.25.2
package com.subjectmapping;

public interface GetSubjectMappingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:subjectmapping.GetSubjectMappingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
