name: 'Generate'

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - run: |
          make toolcheck
          make proto-generate
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          # git push
