name: "Golang Checks"

on:
  pull_request:
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
  vulncheck:
    name: vulncheck
    runs-on: ubuntu-latest
    steps:
      - name: govluncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: 'go.mod'