name: "Proto Checks"

on:
  pull_request:
    branches:
      - main
jobs:
  buflint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      # Run lint only in the `proto` sub-directory
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
  bufbreaking:
    name: Buf Breaking Change Detection
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v2
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
      # Run breaking change detection against the `main` branch
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: 'https://github.com/opentdf/opentdf-v2-poc.git#branch=main'