on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      AUTOMATION_KEY:
        required: true
    inputs:
      # https://github.com/korthout/backport-action/#conflict_resolution
      conflict_resolution:
        default: "draft_commit_conflicts"
        type: string
      # https://github.com/korthout/backport-action/#pull_title
      pull_title:
        default: "${pull_title} [backport to ${target_branch}]"
        type: string

# Default empty permissions for all jobs
permissions: {}

jobs:
  backport:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:

      - name: "Generate a GitHub app token"
        id: generate-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.AUTOMATION_KEY }}

      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true
          token: ${{ steps.generate-token.outputs.token }}

      - name: "Create backport pull requests"
        id: backport
        uses: korthout/backport-action@436145e922f9561fc5ea157ff406f21af2d6b363 # v3.2.0
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          pull_title: ${{ inputs.pull_title }}
          experimental: >
            {
              "conflict_resolution": "${{ inputs.conflict_resolution }}"
            }

      - name: "Sign backport-action commits"
        if: ${{ steps.backport.outputs.created_pull_numbers != '' }}
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          PULL_NUMBERS: ${{ steps.backport.outputs.created_pull_numbers }}
        uses: opentdf/platform/.github/actions/sign-github-app-commit@main

      - name: "Output failed backports"
        if: ${{ steps.backport.outputs.was_successful == 'false' }}
        env:
          TARGETS: ${{ steps.backport.outputs.was_successful_by_target }}
        run: |
          echo -e "Backports were successful:\n$TARGETS" | tee -a "$GITHUB_STEP_SUMMARY"
          exit 1
